### PR TITLE
Switch website to GitHub pages

### PR DESCRIPTION
**Pull request by fingolfin**
The website will be / is at <https://gap-packages.github.io/automgrp/>.

The website is based on GitHub Pages  and its code is in the `gh-pages` branch of this repository; the content of that is based on https://github.com/gap-system/GitHubPagesForGAP where you can also find a README that explains some more.

The idea is that later on uses the `release` script from https://github.com/gap-system/ReleaseTools to make package releases, and that tool also takes care of updating the website for you.

### CODE REVIEW

**Comment by dsavchuk** [comment]
Dear Max,

A quick question on the review. Am I expected to write something that I
understood the procedures? Or this is only for informational purposes?

I will also reply to your other email later today.

Thanks!
Dima

**Comment by fingolfin** [comment]
@dsavchuk No action from you is *necessary*, I merely wanted to give you the opportunity to ask questions, request changes, or simply ask us to "slow down". If you say the word, I can complete everything right away.

The thing is, while we are happy to do all this, of course this is still your package, and you may rightfully say "hey, wait a moment, I'd like to understand this and that better, let me do it". Which is fine. It's also OK to not say that, and let us do it ;-)

**Comment by fingolfin** [comment]
@dsavchuk since I haven't heard anymore from you, I'll now go ahead and merge this.

**Comment by dsavchuk** [comment]
Thank you Max,

Sorry - yes. I will look into it when I will be making a new releases in
this case.

I appreciate your help!
Dima

**Pull request merged**
